/** @format */
import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";

import { AntdRegistry } from "@ant-design/nextjs-registry";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Connecting Communication & Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Head>
        <link
          rel='icon'
          type='image/x-icon'
          href='/favicon.ico'
          sizes='16x16'
        />
      </Head>

      <body className={inter.className}>
        <Header />
        <AntdRegistry>{children}</AntdRegistry>
        <Footer />
      </body>
    </html>
  );
}
