/** @format */
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AntdRegistry } from "@ant-design/nextjs-registry";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Connecting Communication & Solutions",
  description: "Generated by create next app",
  icons: ["/favicon.ico"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <AntdRegistry>{children}</AntdRegistry>
        <Footer />
      </body>
    </html>
  );
}
